[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1"
zip = { version = "6.0.0", features = ["deflate", "aes-crypto"] }
toml = "0.9.8"
trie-rs = "0.4.2"
